/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    predios: Predio;
    eventos: Evento;
    productos: Producto;
    zonas: Zona;
    'email-templates': EmailTemplate;
    'tipos-evento': TiposEvento;
    categorias: Categoria;
    'tipos-explotacion': TiposExplotacion;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    predios: PrediosSelect<false> | PrediosSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    productos: ProductosSelect<false> | ProductosSelect<true>;
    zonas: ZonasSelect<false> | ZonasSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'tipos-evento': TiposEventoSelect<false> | TiposEventoSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    'tipos-explotacion': TiposExplotacionSelect<false> | TiposExplotacionSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    configuracion: Configuracion;
  };
  globalsSelect: {
    configuracion: ConfiguracionSelect<false> | ConfiguracionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      recordatorios: TaskRecordatorios;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  nombre: string;
  role: 'UAGV' | 'URT' | 'UE';
  /**
   * 10 dígitos
   */
  telefono?: string | null;
  tipoDocumento?: ('CC' | 'NIT') | null;
  numeroDocumento?: string | null;
  /**
   * Solo personal interno (UAGV/URT)
   */
  cargo?: string | null;
  /**
   * Solo URT — base del filtro de acceso por zona (09-modelo-permisos).
   */
  zonas?: (string | Zona)[] | null;
  /**
   * Desactivar impide login pero conserva el historial.
   */
  activo?: boolean | null;
  /**
   * Marcado al abrir el enlace del correo de verificación.
   */
  emailVerificado?: boolean | null;
  tokenVerificacion?: string | null;
  /**
   * Capturado en login (HU-1.2): SO, navegador, ubicación aprox.
   */
  dispositivo?: {
    so?: string | null;
    navegador?: string | null;
    ubicacion?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zonas".
 */
export interface Zona {
  id: string;
  /**
   * Departamento / zona.
   */
  nombre: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predios".
 */
export interface Predio {
  id: string;
  nombre: string;
  /**
   * Opcional. Si se deja vacío se infiere por categorías de animales. TODO(D-2): falta la tabla de mapeo categorías→explotación; sin ella NO se infiere (campo queda nulo).
   */
  tipoExplotacion?: (string | null) | TiposExplotacion;
  direccion?: string | null;
  vereda: string;
  municipio: string;
  departamento: string | Zona;
  veterinario?: {
    nombre?: string | null;
    telefono?: string | null;
    correo?: string | null;
  };
  /**
   * UE dueño del predio. "Cambiar responsable" (HU-12.2) reasigna sin perder historial.
   */
  responsable?: (string | null) | User;
  /**
   * Soft-delete: deshabilitar oculta al UE pero conserva datos.
   */
  habilitado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-explotacion".
 */
export interface TiposExplotacion {
  id: string;
  nombre: string;
  /**
   * Soft-delete: desactivar en vez de borrar si está en uso (D-3).
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: string;
  predio: string | Predio;
  /**
   * Denormalizado desde el predio para el filtro de acceso del UE.
   */
  responsable?: (string | null) | User;
  tipoEvento: string | TiposEvento;
  producto?: (string | null) | Producto;
  /**
   * Obligatorio si el producto es "Otra marca" (trazabilidad). No programa recordatorio.
   */
  otraMarcaNombre?: string | null;
  fecha: string;
  categorias?:
    | {
        categoria: string | Categoria;
        cantidad: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Derivado = fecha + intervalo del producto. Lo calcula el hook.
   */
  proximaFecha?: string | null;
  /**
   * false si "Otra marca" o producto sin recordatorio.
   */
  recordatorioProgramado?: boolean | null;
  /**
   * Fechas de envío de los correos de HU-09.
   */
  recordatorios?: {
    enviado3dias?: string | null;
    enviado0dias?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-evento".
 */
export interface TiposEvento {
  id: string;
  nombre: string;
  /**
   * Soft-delete: desactivar en vez de borrar si está en uso (D-3).
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos".
 */
export interface Producto {
  id: string;
  nombre: string;
  tipoEvento: string | TiposEvento;
  /**
   * Intervalo hasta el próximo recordatorio.
   */
  intervalo?: {
    valor?: number | null;
    unidad?: ('dias' | 'meses') | null;
  };
  /**
   * Si false, este producto NO programa recordatorio. TODO(D-4): definir para "Carbones".
   */
  programaRecordatorio?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: string;
  nombre: string;
  /**
   * Soft-delete: desactivar en vez de borrar si está en uso (D-3).
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: string;
  nombre: string;
  /**
   * Identificador estable usado por el job (p. ej. recordatorio-3-dias, recordatorio-0-dias).
   */
  clave: string;
  asunto: string;
  cuerpo: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Texto alternativo (accesibilidad).
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'recordatorios';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'recordatorios') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'predios';
        value: string | Predio;
      } | null)
    | ({
        relationTo: 'eventos';
        value: string | Evento;
      } | null)
    | ({
        relationTo: 'productos';
        value: string | Producto;
      } | null)
    | ({
        relationTo: 'zonas';
        value: string | Zona;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: string | EmailTemplate;
      } | null)
    | ({
        relationTo: 'tipos-evento';
        value: string | TiposEvento;
      } | null)
    | ({
        relationTo: 'categorias';
        value: string | Categoria;
      } | null)
    | ({
        relationTo: 'tipos-explotacion';
        value: string | TiposExplotacion;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  role?: T;
  telefono?: T;
  tipoDocumento?: T;
  numeroDocumento?: T;
  cargo?: T;
  zonas?: T;
  activo?: T;
  emailVerificado?: T;
  tokenVerificacion?: T;
  dispositivo?:
    | T
    | {
        so?: T;
        navegador?: T;
        ubicacion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "predios_select".
 */
export interface PrediosSelect<T extends boolean = true> {
  nombre?: T;
  tipoExplotacion?: T;
  direccion?: T;
  vereda?: T;
  municipio?: T;
  departamento?: T;
  veterinario?:
    | T
    | {
        nombre?: T;
        telefono?: T;
        correo?: T;
      };
  responsable?: T;
  habilitado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  predio?: T;
  responsable?: T;
  tipoEvento?: T;
  producto?: T;
  otraMarcaNombre?: T;
  fecha?: T;
  categorias?:
    | T
    | {
        categoria?: T;
        cantidad?: T;
        id?: T;
      };
  proximaFecha?: T;
  recordatorioProgramado?: T;
  recordatorios?:
    | T
    | {
        enviado3dias?: T;
        enviado0dias?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos_select".
 */
export interface ProductosSelect<T extends boolean = true> {
  nombre?: T;
  tipoEvento?: T;
  intervalo?:
    | T
    | {
        valor?: T;
        unidad?: T;
      };
  programaRecordatorio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zonas_select".
 */
export interface ZonasSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  nombre?: T;
  clave?: T;
  asunto?: T;
  cuerpo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-evento_select".
 */
export interface TiposEventoSelect<T extends boolean = true> {
  nombre?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipos-explotacion_select".
 */
export interface TiposExplotacionSelect<T extends boolean = true> {
  nombre?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion".
 */
export interface Configuracion {
  id: string;
  /**
   * Se muestra al usuario en "¿Olvidaste tu contraseña?" (la recuperación es manual por diseño).
   */
  recuperacion?: {
    /**
     * Teléfono/WhatsApp del asesor AGV.
     */
    telefono?: string | null;
    /**
     * Correo de contacto (opcional).
     */
    correo?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion_select".
 */
export interface ConfiguracionSelect<T extends boolean = true> {
  recuperacion?:
    | T
    | {
        telefono?: T;
        correo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecordatorios".
 */
export interface TaskRecordatorios {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}